export default {
  // UPDATE_CARD_BACKGROUND: 'UPDATE_CARD_BACKGROUND',
  UPDATE_CARD_TYPE: 'UPDATE_CARD_TYPE',
  UPDATE_NUMBER_WITH_MASK: 'UPDATE_NUMBER_WITH_MASK',
  UPDATE_TEXT: 'UPDATE_TEXT',
  UPDATE_NUMBER_SELECT: 'UPDATE_NUMBER_SELECT'
};
